theme: jekyll-theme-chirpy

lang: en
timezone: Europe/Athens

title: "Marootinos Blog"
tagline: "Ideas, Chess & Dev"
description: >-
  Personal blog about ideas, chess, and software development.

url: "https://marootinos.github.io"
baseurl: ""

github:
  username: Marootinos

social:
  name: Marootinos
  email: your-real-email@example.com
  links:
    - https://github.com/marootinos

avatar: "/assets/Brook.png"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
      author: Marootinos
